[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=2.30.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
    "resend>=2.21.0",
]
